<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\UserRole;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property UserRole $role
 * @property bool $is_active
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, EbdClass> $teachingClasses
 * @property-read \Illuminate\Database\Eloquent\Collection<int, LessonRecord> $lessonRecords
 * @property-read \Illuminate\Database\Eloquent\Collection<int, AuditLog> $auditLogs
 */
class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'congregation_id',
        'name',
        'email',
        'password',
        'role',
        'is_active',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string|class-string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'role' => UserRole::class,
            'is_active' => 'boolean',
        ];
    }

    /**
     * Congregação à qual este usuário pertence.
     */
    public function congregation(): BelongsTo
    {
        return $this->belongsTo(Congregation::class, 'congregation_id');
    }

    /**
     * Classes assigned to this teacher.
     */
    public function teachingClasses(): BelongsToMany
    {
        return $this->belongsToMany(EbdClass::class, 'class_teacher', 'user_id', 'class_id')
            ->withPivot('created_at');
    }

    /**
     * Lessons registered by this user.
     */
    public function lessonRecords(): HasMany
    {
        return $this->hasMany(LessonRecord::class, 'registered_by');
    }

    /**
     * Audit logs generated by this user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class, 'user_id');
    }

    public function isAdmin(): bool
    {
        return $this->role === UserRole::ADMIN;
    }

    public function isSecretario(): bool
    {
        return $this->role === UserRole::SECRETARIO;
    }

    public function isProfessor(): bool
    {
        return $this->role === UserRole::PROFESSOR;
    }
}
